
						var subjectObject = {
							"OC" : {
								"Brahmin" : [],
								"Kamma" : [],
								"Kapu / Balija" : [],
								"Komati" : [],
								"Raju" : [],
								"Reddy" : [],
								"Velama" : []
							},
							"BC-A" : {
								"Agnikulakshatriya" : [],
								"Bahurupi" : [],
								"Balasanthu" : [],
								"Banda" : [],
								"Bandara" : [],
								"Bedar" : [],
								"Bestha" : [],
								"Bhajantri" : [],
								"Boya" : [],
								"Budabukkala" : [],
								"Chakali" : [],
								"Chopemari" : [],
								"Chunduvallu" : [],
								"Dasari" : [],
								"Devaravandlu" : [],
								"Dommara" : [],
								"Gangaputra" : [],
								"Gangavar" : [],
								"Gangiredlavaru" : [],
								"Goondla" : [],
								"Gudala" : [],
								"Jalari" : [],
								"Jangam" : [],
								"Jogi" : [],
								"Joshinandiwalas" : [],
								"Kaikadi" : [],
								"Kalinga" : [],
								"Kanjara-bhatta" : [],
								"Katipapala" : [],
								"Kirataka" : [],
								"Kopmare" : [],
								"Korcha" : [],
								"Kunapuli" : [],
								"Mahendra" : [],
								"Mandula" : [],
								"Mangala" : [],
								"Mangali" : [],
								"Medari" : [],
								"Mehtar" : [],
								"Modibanda" : [],
								"Mondipatta" : [],
								"Mondivaru" : [],
								"Mutyalammavandlu" : [],
								"Nakkala" : [],
								"Nayi-brahmin" : [],
								"Nettikotala" : [],
								"Neyyala" : [],
								"Nirshikari" : [],
								"Nishadi" : [],
								"Nokkar" : [],
								"Odde" : [],
								"Oddilu" : [],
								"Palli" : [],
								"Pallikapu" : [],
								"Pallireddi" : [],
								"Pambala" : [],
								"Pamula" : [],
								"Pardhi" : [],
								"Pariki Muggul" : [],
								"Pattapu" : [],
								"Peddaboya" : [],
								"Peddammavandlu" : [],
								"Pitchiguntla" : [],
								"Rajaka" : [],
								"Reddika" : [],
								"Talayari" : [],
								"Vaddelu" : [],
								"Vaddi" : [],
								"Valmiki" : [],
								"Vamsharaj" : [],
								"Vannar" : [],
								"Vannekapu" : [],
								"Vannereddi" : [],
								"Vanyakulakshatriya" : [],
								"Veerabhadreeya" : [],
								"Veeramushti" : [],
								"Yata" : [],
								"Yellammavandlu" : [],
								"Yellapi" : []
							},
							"BC-B" : {
								"Achukatlavandlu" : [],
								"Aryakshatriya" : [],
								"Ausula" : [],
								"Balija" : [],
								"Chitrakara" : [],
								"Chittari" : [],
								"Devanga" : [],
								"Devathilakula" : [],
								"Dudekula" : [],
								"Ediga" : [],
								"Gamalla" : [],
								"Gandla" : [],
								"Giniyar" : [],
								"Goud" : [],
								"Goundla" : [],
								"Gowda" : [],
								"Jandra" : [],
								"Kaikala" : [],
								"Kaikolan" : [],
								"Kalalee" : [],
								"Kammari" : [],
								"Kamsali" : [],
								"Kanchari" : [],
								"Karikalabhakthulu" : [],
								"Karne Bhakthulu" : [],
								"Khatri" : [],
								"Kulala" : [],
								"Kummara" : [],
								"Kurni" : [],
								"Kuruba" : [],
								"Kuruma" : [],
								"Laddaf" : [],
								"Nagavaddilu" : [],
								"Nakhas" : [],
								"Neelakanthi" : [],
								"Noorbasha" : [],
								"Nossi" : [],
								"Padmasali" : [],
								"Patkar" : [],
								"Pattusali" : [],
								"Perika" : [],
								"Perika Balija" : [],
								"Pinjari" : [],
								"Puragiri Kshatriya" : [],
								"Sali" : [],
								"Salivahana" : [],
								"Salivan" : [],
								"Sangunther" : [],
								"Segidi" : [],
								"Senapathulu" : [],
								"Sengundam" : [],
								"Settibalija" : [],
								"Silpis" : [],
								"Srisayana" : [],
								"Swakulasali" : [],
								"Telikula" : [],
								"Thogata" : [],
								"Thogata Sali" : [],
								"Thogata Veera Kshatriya" : [],
								"Thogati" : [],
								"Vadla" : [],
								"Vadra" : [],
								"Vadrangi" : [],
								"Viswabrahmin" : [],
								"Viswakarma" : []
							},
							"BC-C" : {
								"Converted Christian" : []
							},

							"BC-D" : {
								"Agaru" : [],
								"Arekatika" : [],
								"Atagara" : [],
								"Bhatraju" : [],
								"Bhavasara Kshatriya" : [],
								"Bukka" : [],
								"Chattada Sri Vaishnava" : [],
								"Chippolu" : [],
								"Dasari" : [],
								"Ganika" : [],
								"Gavara" : [],
								"Godaba" : [],
								"Golla" : [],
								"Hatkar" : [],
								"Jakkala" : [],
								"Jingar" : [],
								"Kachi" : [],
								"Kalavanthula" : [],
								"Kandra" : [],
								"Katika" : [],
								"Koppulavelama" : [],
								"Koshti" : [],
								"Krishnabalija" : [],
								"Mali" : [],
								"Mathura" : [],
								"Mera" : [],
								"Mudiraj" : [],
								"Munnurukapu" : [],
								"Mutrasi" : [],
								"Nagavamsa" : [],
								"Nagavamsam" : [],
								"Nelli" : [],
								"Passi" : [],
								"Poosala" : [],
								"Rangrez" : [],
								"Sadhuchetty" : [],
								"Sagara" : [],
								"Satani" : [],
								"Suryabalija" : [],
								"Tammali" : [],
								"Tenugollu" : [],
								"Turupukapus" : [],
								"Uppara" : [],
								"Vanjara" : [],
								"Vanjari" : [],
								"Yadava" : []
							},

							"SC" : {
								"Adi Andhra" : [],
								"Adi Dravida" : [],
								"Anamuk" : [],
								"Aray Mala" : [],
								"Arundhatiya" : [],
								"Arwa Mala" : [],
								"Bariki" : [],
								"Bavuri" : [],
								"Bindla" : [],
								"Byagara, Byagari" : [],
								"Chachati" : [],
								"Chalavadi" : [],
								"Chamar, Mochi, Muchi, Chamar-Ravidas, Chamar-Rohidas" : [],
								"Chambhar" : [],
								"Chandala" : [],
								"Dakkal, Dokkalwar" : [],
								"Dandasi" : [],
								"Dhor" : [],
								"Dom, Dombara, Paidi, Pano" : [],
								"Ellamalawar, Yellammalawandlu" : [],
								"Ghasi, Haddi, Relli, Chachandi" : [],
								"Godagali, Godagula " : [],
								"Godari" : [],
								"Gosangi" : [],
								"Holeya" : [],
								"Holeya Dasari" : [],
								"Jaggali" : [],
								"Jambuvulu" : [],
								"Kolupulvandlu, Pambada, Pambanda, Pambala" : [],
								"Madasi Kuruva, Madari Kuruva" : [],
								"Madiga" : [],
								"Madiga Dasu, Mashteen" : [],
								"Mahar" : [],
								"Mala, Mala Ayawaru" : [],
								"Mala Dasari" : [],
								"Mala Dasu" : [],
								"Mala Hannai" : [],
								"Malajangam" : [],
								"Mala Masti" : [],
								"Mala Sale, Netkani" : [],
								"Mala Sanyasi" : [],
								"Mang" : [],
								"Mang Garodi" : [],
								"Manne" : [],
								"Mashti" : [],
								"Matangi" : [],
								"Mehtar" : [],
								"Mitha Ayyalvar" : [],
								"Mundala" : [],
								"Paky, Moti, Thoti" : [],
								"Pamidi" : [],
								"Panchama, Pariah" : [],
								"Relli" : [],
								"Samagara" : [],
								"Samban" : [],
								"Sapru" : [],
								"Sindhollu, Chindollu" : [],
								"Yatala" : [],
								"Valluvan" : []
							},

							"ST" : {
								"Andh, Sadhu Andh" : [],
								"Bagata" : [],
								"Bhil" : [],
								"Chenchu" : [],
								"Gadabas, Bodo, Gadaba, Gutob, Gadaba, Kallayi, Gadaba, Parangi, Gadaba, Kathera, Gadaba, Kapu, Gadaba" : [],
								"Gond, Naikpod, Rajgond, Koitur" : [],
								"Goudu (in the Agency tracts)" : [],
								"Hill Reddis" : [],
								"Jatapus" : [],
								"Kammara" : [],
								"Kattunayakan" : [],
								"Kolam, Kolawar" : [],
								"Konda Dhoras, Kubi" : [],
								"Konda Kapus" : [],
								"Kondareddis" : [],
								"Kondhs, Kodi, Kodhu, Desaya, Kondhs, Dongria, Kondhs, Kuttiya, Kondhs, Tikiria, Kondhs, Yenity, Kondhs, Kuvinga" : [],
								"Kotia, Bentho Oriya, Bartika, Dulia, Holva, Sanrona, Sidhopaiko " : [],
								"Koya, Doli Koya, Gutta Koya, Kammara Koya, Musara Koya,Oddi, Koya, Pattidi Koya, Rajah, Rasha Koya, Lingadhari Koya (ordinary), Kottu, Koya, Bhine Koya, Rajkoya" : [],
								"Kulia" : [],
								"Malis" : [],
								"Manna Dhora" : [],
								"Mukha Dhora, Nooka Dhora" : [],
								"Nayaks (in the Agency tracts)" : [],
								"Pardhan" : [],
								"Porja, Parangiperja" : [],
								"Reddi Dhoras" : [],
								"Rona, Rena" : [],
								"Savaras, Kapu, Savaras, Maliya, Savaras, Khutto, Savaras" : [],
								"Sugalis, Lambadis, Banjara" : [],
								"Valmiki " : [],
								"Yenadis, Chella, Yenadi, Kappala, Yenadi, Manchi, Yenadi, Reddi, Yenadi" : [],
								"Yerukulas, Koracha, Dabba Yerukula, Kunchapuri, Yerukula, Uppu, Yerukula" : [],
								"Nakkala, Kurvikaran" : [],
								"Dhulia, Paiko, Putiya " : []
							},
							"Minority" : {
								"Sayed" : [],
								"shaik" : [],
								"patan" : []

							}

						}
						window.onload = function() {
							var subjectSel = document.getElementById("subject");
							var topicSel = document.getElementById("topic");
							var chapterSel = document.getElementById("chapter");
							for ( var x in subjectObject) {
								subjectSel.options[subjectSel.options.length] = new Option(
										x, x);
							}
							subjectSel.onchange = function() {
								//empty Chapters- and Topics- dropdowns
								topicSel.length = 1;
								//display correct values
								for ( var y in subjectObject[this.value]) {
									topicSel.options[topicSel.options.length] = new Option(
											y, y);
								}
							}

						}
					